name: cuda_12.1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - accelerate=0.27.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - albumentations=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - appdirs=1.4.4
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - blas=1.0
  - blosc=1.21.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.26.0
  - c-blosc2=2.13.2
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask-core=2024.2.0
  - datasets=2.14.4
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.7
  - docker-pycreds=0.4.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.41
  - glib=2.78.3
  - glib-tools=2.78.3
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - graphite2=1.3.13
  - grpcio=1.54.3
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.37
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - huggingface_hub=0.20.2
  - icu=70.1
  - idna=3.6
  - imagecodecs=2023.1.23
  - imagecodecs-lite=2019.12.3
  - imageio=2.34.0
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.2
  - ipython=8.21.0
  - ipywidgets=8.1.2
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - kornia=0.7.1
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.2
  - libarrow=12.0.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcups=2.3.3
  - libcurand=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.54.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.4
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.42
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsentencepiece=0.1.99
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.4
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.15
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nltk=3.8.1
  - nspr=4.35
  - nss=3.97
  - numpy=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.5
  - orc=1.9.0
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=2.2.0
  - parso=0.8.3
  - partd=1.4.1
  - pathtools=0.1.2
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - protobuf=4.21.12
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pyarrow=12.0.1
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - qudida=0.0.4
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.12.25
  - requests=2.31.0
  - s2n=1.3.49
  - safetensors=0.4.2
  - scikit-image=0.22.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - sentry-sdk=1.40.4
  - setproctitle=1.3.3
  - setuptools=69.0.3
  - sip=6.7.12
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.3.0
  - tifffile=2023.8.12
  - timm=0.9.12
  - tk=8.6.13
  - tokenizers=0.15.1
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.15.2
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.14.1
  - transformers=4.39.3
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - ucx=1.14.1
  - urllib3=2.2.0
  - wandb=0.16.3
  - wcwidth=0.2.13
  - werkzeug=3.0.2
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
